POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username" : "Shayla",
    "name" : "Shayla Sharmin Urmi",
    "password" : "12345"
}

###
GET http://localhost:3001/api/users