GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "I am a fan of Real Madrid",
  "author": "Mateo Messi",
  "url": "http://messimybaap.es",
  "likes": 114,
  "userId" : "620cb7392de178642986657f"
}

###

DELETE http://localhost:3003/api/blogs/620d0296ed106ea647d5fb65